# -*- coding: utf-8 -*-

# ============================================================
# Node identity
# ============================================================

NODE_ID = "yaglabterm02"

# EASEL own node ID
# yaglabterm01: "0001"
# yaglabterm02: "0002"
OWN_ID = "0002"

LOCAL_BST_ID = 200

# ============================================================
# Serial port
# ============================================================

SERIAL_PORT = "/dev/lora0"
BAUDRATE = 115200
SERIAL_TIMEOUT_SEC = 0.5

# ============================================================
# EASEL ES920LR radio settings
# ============================================================
# Command spec:
#   bw:
#     3 = 62.5 kHz
#     4 = 125 kHz
#     5 = 250 kHz
#     6 = 500 kHz
#
#   sf:
#     7 - 12
#
#   channel:
#     62.5/125 kHz: 1 - 15
#     250 kHz:      1 - 7
#     500 kHz:      1 - 5
#
# Current test setting:
#   500 kHz, SF8, channel 1

BW = "6"
SF = "8"
CH = "1"

PAN_ID = "ABCD"
DST_ID = "FFFF"   # Broadcast

ACK = "2"         # 1: ON, 2: OFF
RETRY = "0"
TRANSMODE = "1"   # 1: Payload, 2: Frame
FORMAT = "1"      # 1: ASCII, 2: BINARY

RCVID = "2"       # 1: ON, 2: OFF
RSSI = "2"        # 1: ON, 2: OFF
POWER = "13"      # -4 to 13 dBm

# Commands sent before start.
# Keep this list as the single source of truth for EASEL setup.
EASEL_CONFIG_COMMANDS = [
    ("bw", BW),
    ("sf", SF),
    ("channel", CH),
    ("panid", PAN_ID),
    ("ownid", OWN_ID),
    ("dstid", DST_ID),
    ("ack", ACK),
    ("retry", RETRY),
    ("transmode", TRANSMODE),
    ("format", FORMAT),
    ("rcvid", RCVID),
    ("rssi", RSSI),
    ("power", POWER),
]

# ============================================================
# Redis
# ============================================================

REDIS_ENABLED = True
REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
REDIS_DB = 0

REDIS_RAW_TX = "lora:raw:tx"
REDIS_RAW_RX = "lora:raw:rx"
REDIS_EVENT = "lora:event"
REDIS_STATE = "lora:state:radio"

# ============================================================
# Safety
# ============================================================

MAX_TX_LINE_LEN = 80

# ============================================================
# Slotted ALOHA self-position beacon
# ============================================================

SLOTTED_ENABLED = True

# 5秒に1回、自ノード位置を送信
FRAME_SEC = 5.0

# 10台程度を想定して 0.5秒slot × 10 slots
SLOT_SEC = 0.5

# slotの端を避けるため、slot開始からこの秒数だけ待って送る
TX_GUARD_SEC = 0.05

# 1 frameにつき1回だけTX
SELF_BEACON_ENABLED = True

# RedisからGPS状態を読む
REDIS_GPS_STATE_KEY = "state:self"

# 他ノード状態保存先
REDIS_NODE_PREFIX = "lora:nodes:"
REDIS_NODE_TTL_SEC = 60

# RX履歴
REDIS_RAW_RX = "lora:raw:rx"
REDIS_EVENT = "lora:event"
REDIS_STATE = "lora:state:radio"

# 最大送信長
MAX_TX_LINE_LEN = 80

# ============================================================
# Redis cleanup on daemon startup
# ============================================================

REDIS_CLEAN_ON_START = True

REDIS_CLEAN_PATTERNS = [
    "lora:raw:*",
    "lora:event",
    "lora:state:radio",
    "lora:nodes:*",
]
# ============================================================
# BST-ID settings
# ============================================================

BST_ZX = 16
BST_ZY = 16

# For now, LoRa beacon uses official BST-ID generated by bst-id-main.
BEACON_FORMAT = "BST_ID"

