# -*- coding: utf-8 -*-
import hashlib
import json
import math
import time
from typing import Any, Dict, Optional, Tuple

import redis

import config
from easel_radio import EaselRadio
from bst_codec import (
    encode_xy_bst_id,
    decode_bst_hex_to_int,
    bst_hex_to_bin,
    estimate_tile_center_from_latlon,
)

def now_ms() -> int:
    return int(time.time() * 1000)


def json_dumps(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def json_loads_safe(s: Optional[str]) -> Optional[Dict[str, Any]]:
    if not s:
        return None
    try:
        return json.loads(s)
    except Exception:
        return None


def get_slot_count() -> int:
    return max(1, int(round(config.FRAME_SEC / config.SLOT_SEC)))


def current_frame_and_slot() -> Tuple[int, int, float]:
    """
    Returns:
      frame_id,
      current_slot,
      offset_in_slot_sec
    """
    t = time.time()
    frame_id = int(math.floor(t / config.FRAME_SEC))
    frame_pos = t - frame_id * config.FRAME_SEC

    slot = int(frame_pos // config.SLOT_SEC)
    slot_offset = frame_pos - slot * config.SLOT_SEC

    return frame_id, slot, slot_offset


def choose_tx_slot(node_id: str, frame_id: int) -> int:
    """
    Deterministic pseudo-random slot selection.
    Same node chooses one slot per frame, but changes each frame.
    """
    slot_count = get_slot_count()
    seed = f"{node_id}:{frame_id}".encode("utf-8")
    h = hashlib.blake2s(seed, digest_size=4).digest()
    v = int.from_bytes(h, "big")
    return v % slot_count


def get_gps_state(r: redis.Redis) -> Dict[str, Any]:
    """
    Read latest local GPS/self state from Redis.
    If unavailable, use dummy values.
    """
    state = json_loads_safe(r.get(config.REDIS_GPS_STATE_KEY)) or {}

    lat = state.get("lat")
    lon = state.get("lon")
    alt = state.get("alt")

    # null対策
    if lat is None:
        lat = 0.0
    if lon is None:
        lon = 0.0
    if alt is None:
        alt = 0.0

    return {
        "lat": float(lat),
        "lon": float(lon),
        "alt": float(alt),
        "speed_mps": float(state.get("speed_mps") or state.get("speed") or 0.0),
        "heading_deg": float(state.get("heading_deg") or state.get("track") or 0.0),
        "fix_status": state.get("fix_status", ""),
        "satellites_used": state.get("satellites_used"),
        "hdop": state.get("hdop"),
    }

def short_node_id(node_id: str) -> str:
    """
    Keep packet short.
    yaglabterm01 -> 01
    yaglabterm02 -> 02
    otherwise last 2 chars.
    """
    if node_id.endswith("01"):
        return "01"
    if node_id.endswith("02"):
        return "02"
    return node_id[-2:]


def encode_node_status(node_id: str, seq: int, gps: Dict[str, Any]) -> str:
    """
    Official BST-ID based node status beacon.

    Format:
      B,<node2>,<seq>,<bit_len>,<bst_hex>,<alt>,<spd10>,<hdg>

    Example:
      B,01,12,46,3C7A91F023A1,210,0,0

    The bst_hex is generated by bst-id-main.
    """

    lat = float(gps["lat"])
    lon = float(gps["lon"])

    bst = encode_xy_bst_id(
        lat=lat,
        lon=lon,
        zx=config.BST_ZX,
        zy=config.BST_ZY,
    )

    alt_i = int(round(float(gps.get("alt", 0.0))))
    spd_i = int(round(float(gps.get("speed_mps", 0.0)) * 10))
    hdg_i = int(round(float(gps.get("heading_deg", 0.0))))

    node2 = short_node_id(node_id)

    return (
        f"B,{node2},{seq},"
        f"{bst['bit_len']},{bst['bst_hex']},"
        f"{alt_i},{spd_i},{hdg_i}"
    )

def full_node_id(node2: str) -> str:
    if node2 == "01":
        return "yaglabterm01"
    if node2 == "02":
        return "yaglabterm02"
    return node2


def decode_node_status(line: str) -> Optional[Dict[str, Any]]:
    """
    Decode node status packets.

    Supported:
      B,<node2>,<seq>,<bit_len>,<bst_hex>,<alt>,<spd10>,<hdg>
      N,<node>,<seq>,<latE5>,<lonE5>,<alt>,<spd10>,<hdg>
    """
    try:
        parts = line.strip().split(",")

        if not parts:
            return None

        # Official BST-ID format
        if parts[0] == "B":
            if len(parts) != 8:
                return None

            node_id = full_node_id(parts[1])
            seq = int(parts[2])
            bit_len = int(parts[3])
            bst_hex = parts[4]
            alt = float(parts[5])
            speed_mps = int(parts[6]) / 10.0
            heading_deg = float(parts[7])

            bst_id_int = decode_bst_hex_to_int(bst_hex)
            bst_bin = bst_hex_to_bin(bst_hex, bit_len)

            return {
                "type": "NODE_STATUS",
                "format": "BST_ID",
                "node_id": node_id,
                "seq": seq,
                "bst_id_int": str(bst_id_int),
                "bst_hex": bst_hex,
                "bst_bit_len": bit_len,
                "bst_bin": bst_bin,
                "alt": alt,
                "speed_mps": speed_mps,
                "heading_deg": heading_deg,
                "received_at_ms": now_ms(),
            }

        # Old lat/lon format, kept for compatibility
        if parts[0] == "N":
            if len(parts) != 8:
                return None

            node_id = parts[1]
            seq = int(parts[2])
            lat = int(parts[3]) / 100000.0
            lon = int(parts[4]) / 100000.0
            alt = float(parts[5])
            speed_mps = int(parts[6]) / 10.0
            heading_deg = float(parts[7])

            bst = encode_xy_bst_id(
                lat=lat,
                lon=lon,
                zx=config.BST_ZX,
                zy=config.BST_ZY,
            )

            tile = estimate_tile_center_from_latlon(
                lat=lat,
                lon=lon,
                z=config.BST_ZX,
            )

            return {
                "type": "NODE_STATUS",
                "format": "LATLON",
                "node_id": node_id,
                "seq": seq,
                "lat": lat,
                "lon": lon,
                "alt": alt,
                "speed_mps": speed_mps,
                "heading_deg": heading_deg,
                "bst_id_int": str(bst["bst_id"]),
                "bst_hex": bst["bst_hex"],
                "bst_bit_len": bst["bit_len"],
                "zx": config.BST_ZX,
                "zy": config.BST_ZY,
                "xtile": tile["xtile"],
                "ytile": tile["ytile"],
                "received_at_ms": now_ms(),
            }

        return None

    except Exception as e:
        print(f"[DECODE-ERR] {e} line={line!r}", flush=True)
        return None



def save_rx_line(r: redis.Redis, line: str) -> None:
    obj = {
        "node_id": config.NODE_ID,
        "line": line,
        "received_at_ms": now_ms(),
    }

    r.lpush(config.REDIS_RAW_RX, json_dumps(obj))
    r.ltrim(config.REDIS_RAW_RX, 0, 200)

    r.publish(
        config.REDIS_EVENT,
        json_dumps({
            "event": "rx",
            **obj,
        })
    )

    decoded = decode_node_status(line)
    if decoded:
        key = f"{config.REDIS_NODE_PREFIX}{decoded['node_id']}"
        r.set(key, json_dumps(decoded), ex=config.REDIS_NODE_TTL_SEC)

        r.publish(
            config.REDIS_EVENT,
            json_dumps({
                "event": "node_status",
                **decoded,
            })
        )

def cleanup_redis_on_start(r: redis.Redis) -> None:
    if not getattr(config, "REDIS_CLEAN_ON_START", False):
        return

    patterns = getattr(config, "REDIS_CLEAN_PATTERNS", [])

    deleted_total = 0

    for pattern in patterns:
        cursor = 0
        while True:
            cursor, keys = r.scan(cursor=cursor, match=pattern, count=100)

            if keys:
                deleted = r.delete(*keys)
                deleted_total += deleted
                print(
                    f"[REDIS-CLEAN] pattern={pattern} deleted={deleted}",
                    flush=True
                )

            if cursor == 0:
                break

    print(f"[REDIS-CLEAN] total deleted={deleted_total}", flush=True)
    
def save_radio_state(r: redis.Redis, frame_id: int, slot: int, tx_slot: int) -> None:
    state = {
        "node_id": config.NODE_ID,
        "port": config.SERIAL_PORT,
        "baudrate": config.BAUDRATE,
        "bw": config.BW,
        "sf": config.SF,
        "ch": config.CH,
        "panid": config.PAN_ID,
        "ownid": config.OWN_ID,
        "dstid": config.DST_ID,
        "frame_sec": config.FRAME_SEC,
        "slot_sec": config.SLOT_SEC,
        "slot_count": get_slot_count(),
        "frame_id": frame_id,
        "current_slot": slot,
        "selected_tx_slot": tx_slot,
        "updated_at_ms": now_ms(),
    }
    r.set(config.REDIS_STATE, json_dumps(state))


def main():
    r = redis.Redis(
        host=config.REDIS_HOST,
        port=config.REDIS_PORT,
        db=config.REDIS_DB,
        decode_responses=True,
    )
    
    cleanup_redis_on_start(r)

    radio = EaselRadio(debug=True)

    radio.open()
    radio.configure_from_config()

    print("[SLOTTED-BEACON] started", flush=True)
    print(
        f"[SLOTTED-BEACON] frame={config.FRAME_SEC}s "
        f"slot={config.SLOT_SEC}s slots={get_slot_count()}",
        flush=True,
    )

    seq = 0
    last_tx_frame: Optional[int] = None

    try:
        while True:
            # ----------------------------------------------------
            # RX is always active
            # ----------------------------------------------------
            line = radio.read_line()
            if line:
                save_rx_line(r, line)

            # ----------------------------------------------------
            # Slotted TX
            # ----------------------------------------------------
            frame_id, slot, slot_offset = current_frame_and_slot()
            tx_slot = choose_tx_slot(config.NODE_ID, frame_id)

            save_radio_state(r, frame_id, slot, tx_slot)

            should_tx = (
                config.SELF_BEACON_ENABLED
                and last_tx_frame != frame_id
                and slot == tx_slot
                and slot_offset >= config.TX_GUARD_SEC
            )

            if should_tx:
                gps = get_gps_state(r)
                payload = encode_node_status(config.NODE_ID, seq, gps)

                ok = radio.send_payload(payload, max_len=config.MAX_TX_LINE_LEN)

                r.publish(
                    config.REDIS_EVENT,
                    json_dumps({
                        "event": "tx_node_status",
                        "node_id": config.NODE_ID,
                        "seq": seq,
                        "payload": payload,
                        "ok": ok,
                        "frame_id": frame_id,
                        "slot": slot,
                        "tx_slot": tx_slot,
                        "sent_at_ms": now_ms(),
                    })
                )

                last_tx_frame = frame_id
                seq += 1

            time.sleep(0.02)

    finally:
        radio.close()


if __name__ == "__main__":
    main()
